---

- name: "delete openshift resources for iot-ui application"
  k8s:
    state: absent
    api_version: "{{ item.api_version }}"
    kind: "{{ item.kind }}"
    namespace: "{{ application_namespace }}"
    name: "{{ item.name }}"
  loop:
    - api_version: apps/v1
      kind: deployment
      name: "{{ iot_ui_application }}"
    - api_version: v1
      kind: service
      name: "{{ iot_ui_application }}"
    - api_version: route.openshift.io/v1
      kind: route
      name: "{{ iot_ui_application }}"
    - api_version: v1
      kind: secret
      name: "{{ iot_ui_secret }}"
    - api_version: v1
      kind: serviceaccount
      name: "{{ iot_ui_service_account }}"
