---

- name: "get service account credentials secret"
  k8s_info:
    api_version: v1
    kind: secret
    namespace: "{{ namespace }}"
    name: "{{ cloud_services_service_account_secret }}"
  register: cloud_service_account_secret

- set_fact:
    cloud_service_account_client_id: "{{ cloud_service_account_secret.resources[0].data.get('client-id') | b64decode }}"
    cloud_service_account_client_secret: "{{ cloud_service_account_secret.resources[0].data.get('client-secret') | b64decode }}"
    cloud_service_account_client_secret_key: "client-secret"
