---

- name: "delete amq mqtt broker"
  k8s:
    state: absent
    api_version: broker.amq.io/v2alpha4
    kind: ActiveMQArtemis
    namespace: "{{ application_namespace }}"
    name: "{{ amq_broker_name }}"
