---

kafka_connect: iot-connect
kafka_connect_version: 2.8.0
kafka_connect_replicas: 0
kafka_connect_imagestream: kafka-connect-build
kafka_connect_imagestream_tag: latest

kafka_connect_requests_cpu: 100m
kafka_connect_requests_memory: 250M
kafka_connect_limits_cpu: 500m
kafka_connect_limits_memory: 1G

kafka_connect_liveness_probe_initial_delay_seconds: 45
kafka_connect_liveness_probe_timeout_seconds: 5
kafka_connect_readiness_probe_initial_delay_seconds: 15
kafka_connect_readiness_probe_timeout_seconds: 5

dbz_connector: dbz-connector
dbz_database_hostname: "{{ iot_postgresql_application }}"
dbz_schema_include_list: public
dbz_table_include_list: public.meter
