
- name: "delete openshift resources for kafka connect application"
  k8s:
    state: absent
    api_version: "{{ item.api_version }}"
    kind: "{{ item.kind }}"
    namespace: "{{ application_namespace }}"
    name: "{{ item.name }}"
  loop:
    - api_version: kafka.strimzi.io/v1beta2
      kind: kafkaconnector
      name: "{{ dbz_connector }}"
    - api_version: kafka.strimzi.io/v1beta2
      kind: kafkaconnect
      name: "{{ kafka_connect }}"
    - api_version: image.openshift.io/v1
      kind: imagestream
      name: "{{ kafka_connect_imagestream }}"
