---

- name: "create openshift resources for iot-graphql-api application"
  k8s:
    state: present
    namespace: "{{ application_namespace }}"
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - "templates/service-account.j2"
    - "templates/deployment.j2"
    - "templates/service.j2"
    - "templates/route.j2"
