---

- name: "set postgresql passwords"
  set_fact: 
    iot_postgresql_password: "{{ lookup('password', '{{ work_dir }}/user chars=ascii_letters length=12') }}"
    iot_postgresql_dbz_password: "{{ lookup('password', '{{ work_dir }}/dbz-user chars=ascii_letters length=12') }}"

- name: "check if postgresql credentials secret exists"
  k8s_info:
    kind: secret
    api_version: v1
    name: "{{ iot_postgresql_credentials_secret }}"
    namespace: "{{ application_namespace }}"
  register: r_iot_postgresql_credentials_secret

- name: "create postgresql credentials secret"
  when: (not r_iot_postgresql_credentials_secret.resources is defined) or (r_iot_postgresql_credentials_secret.resources | length == 0) 
  k8s:
    state: present
    namespace: "{{ application_namespace }}"
    definition: "{{ lookup('template', resource ) | from_yaml }}"
  vars:
    resource: "templates/secret.j2"

- name: "create openshift resources for postgresql"
  k8s:
    state: present
    namespace: "{{ application_namespace }}"
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - "templates/service-account.j2"
    - "templates/pvc.j2"
    - "templates/deployment.j2"
    - "templates/service.j2"
